openapi: 3.0.3

info:
  title: Pagination parameters
  version: 2.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

paths: {}

components:
  parameters:

    limit:
      name: limit
      in: query
      required: false
      description: The maximum number of elements to return.
      schema:
        format: int32
        default: 100
        maximum: 100
        minimum: 0
        type: integer

    offset:
      name: offset
      in: query
      description: The offset of the first element to return.
      schema:
        format: int32
        default: 0
        type: integer

    sort:
      name: sort
      in: query
      description: |
        The sort criteria.

        The default sort order is ascending.
        To specify descending order for a field, a prefix of `-` should be used.

        Multiple sort criteria can be passed.
        The sort criteria will be applied in the order they are passed.
      schema:
        example: -createdDate
