openapi: 3.1.0

info:
  title: GeographicAddress
  version: 2.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
    identifier: Apache-2.0

components:
  schemas:
    GeographicAddress:
      description: |
        Structured textual way of describing how to find a Property in an urban area (country properties are often defined differently).
      allOf:
        - $ref: './Entity.openapi.yaml#/components/schemas/Entity'
      properties:
        city:
          type: string
          description: |
            City the address is in.

            Correspond à la propriété `commune` de l'IPE.
        country:
          type: string
          description: Country the address is in
        locality:
          type: string
          description: |
            An area of defined or undefined boundaries within a local authority or other legislatively defined area,
            usually rural or semi rural in nature.
        postcode:
          type: string
          description: |
            Descriptor for a postal delivery area, used to speed and simplify the delivery of mail (also know as zipcode).

            Correspond à la propriété `code_postal` de l'IPE.
        stateOrProvince:
          type: string
          description: the State or Province that the address is in
        streetName:
          type: string
          description: |
            Name of the street or other street type.

            Correspond à la propriété `nom_voie` de l'IPE.
        streetNr:
          type: string
          description: |
            Number identifying a specific property on a public street. It may be combined with streetNrLast for ranged addresses.

            Correspond à la propriété `numero_voie` de l'IPE.
        streetNrLast:
          type: string
          description: Last number in a range of street numbers allocated to a property
        streetNrSuffix:
          type: string
          description: the first street number suffix
        streetNrLastSuffix:
          type: string
          description: the last street number suffix for a ranged address
        streetSuffix:
          type: string
          description: A modifier denoting a relative direction
        streetType:
          type: string
          description: |
            alley, avenue, boulevard, brae, crescent, drive, highway, lane, terrace, parade, place, tarn, way, wharf, ...

            Correspond à la propriété `type_voie` de l'IPE.
        geographicLocations:
          type: array
          items:
            $ref: './GeographicPoint.openapi.yaml#/components/schemas/GeographicPoint'
          description: |
            Geographic location of the address.
            This is a list of geographic locations, each of which may be associated with a different coordinate system.
