openapi: 3.1.0

info:
  title: GeographicAddress
  version: 2.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
    identifier: Apache-2.0

components:
  schemas:
    GeographicAddress:
      description: |
        Structured textual way of describing how to find a Property in an urban area (country properties are often defined differently).
      allOf:
        - $ref: './Extensible.openapi.yaml#/components/schemas/Extensible'
      properties:
        city:
          type: string
          description: |
            City the address is in.

            Correspond à la propriété `commune` de l'IPE.
        country:
          type: string
          description: Country the address is in
        locality:
          type: string
          description: |
            An area of defined or undefined boundaries within a local authority or other legislatively defined area,
            usually rural or semi rural in nature.
        postcode:
          type: string
          description: |
            Descriptor for a postal delivery area, used to speed and simplify the delivery of mail (also know as zipcode).

            Correspond à la propriété `code_postal` de l'IPE.
        stateOrProvince:
          type: string
          description: the State or Province that the address is in
        streetName:
          type: string
          description: |
            Name of the street or other street type.

            Correspond à la propriété `nom_voie` de l'IPE.
        streetNr:
          type: string
          description: |
            Number identifying a specific property on a public street. It may be combined with streetNrLast for ranged addresses.

            Correspond à la propriété `numero_voie` de l'IPE.
        streetNrLast:
          type: string
          description: Last number in a range of street numbers allocated to a property
        streetNrSuffix:
          type: string
          description: the first street number suffix
        streetNrLastSuffix:
          type: string
          description: the last street number suffix for a ranged address
        streetSuffix:
          type: string
          description: A modifier denoting a relative direction
        streetType:
          type: string
          description: |
            alley, avenue, boulevard, brae, crescent, drive, highway, lane, terrace, parade, place, tarn, way, wharf, ...

            Correspond à la propriété `type_voie` de l'IPE.
        code_insee:
          type: string
          description: |
            Code INSEE de la commune.

            Correspond à la propriété `code_insee` de l'IPE.
        code_hexacle:
          type: string
          description: |
            Code Hexacle de la commune.

            Correspond à la propriété `code_hexacle` de l'IPE.
        code_hexavia:
          type: string
          description: |
            Code Hexavia de la commune.

            Correspond à la propriété `code_hexavia` de l'IPE.
        code_rivoli:
          type: string
          description: |
            Code Rivoli de la commune.

            Correspond à la propriété `code_rivoli` de l'IPE.
        code_ban:
          type: string
