openapi: 3.0.3

info:
  title: Pagination headers
  version: 2.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

paths: {}

components:
  headers:

    X-Result-Count:
      description: Actual number of items returned
      style: simple
      schema:
        format: int32
        type: integer
        example: 42

    X-Total-Count:
      description: Total number of items matching criteria
      style: simple
      schema:
        format: int32
        type: integer
        example: 42
